# docker-compose.yml
#version: "3.8"

services:
  pulsar:
    image: apachepulsar/pulsar:latest
    command: ["bin/pulsar", "standalone"]
    ports:
      - "6650:6650"
      - "8080:8080"

  spark:
    image: bitnami/spark:3.4.1
    ports:
      - "7077:7077"
      - "8081:8081"
    environment:
      - SPARK_MODE=master
    volumes:
      - ./spark_processing.py:/opt/spark_processing.py
